command:
  - uv
  - run
  - scripts/wandb_sweep_agent.py
name: products_sgformer_sweep
method: bayes # random, grid, bayes
metric:
  goal: maximize
  name: test/accuracy
parameters:
  base_config_file:
    values:
      - configs/ogbn_products/sgformer.yml
  model_parameters:
    parameters:
      architecture_parameters:
        parameters:
          dropout:
            values: [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8]
          num_heads:
            values: [1, 2, 4]
      gnn_parameters:
        parameters:
          dropout:
            values: [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8]
      optimizer:
        parameters:
          parameters:
            parameters:
              lr: 
                values: [0.01, 0.005, 0.001, 0.0005, 0.0001]
              weight_decay: 
                values: [0, 0.0001, 0.0005, 0.001, 0.005]


