command:
  - uv
  - run
  - scripts/wandb_sweep_agent.py
name: arxiv_sage_sgd_sweep
method: bayes # random, grid, bayes
metric:
  goal: maximize
  name: test/accuracy
parameters:
  base_config_file:
    values:
      - configs/ogbn_arxiv/sage_sgd.yml
  model_parameters:
    parameters:
      architecture_parameters:
        parameters:
          dropout:
            values: [0.0, 0.1, 0.2, 0.3, 0.4, 0.5]

      optimizer:
        parameters:
          parameters:
            parameters:
              lr: 
                values: [0.03, 0.02, 0.01, 0.008, 0.006, 0.005, 0.003, 0.002, 0.001, 0.0005]
              weight_decay: 
                values: [0, 0.00001, 0.00005, 0.0001, 0.0005, 0.001, 0.002, 0.005, 0.01, 0.05]


