command:
  - uv
  - run
  - scripts/wandb_sweep_agent.py
name: example
method: bayes # random, grid, bayes
metric:
  goal: maximize
  name: test/accuracy
parameters:
  base_config_file: 
    values: 
      - configs/cora/gcn.yml
  model_parameters:
    parameters:
      optimizer:
        parameters:
          optimizer_type: 
            values: [sgd, adam, adamw]
          parameters:
            parameters:
              lr: 
                values: [5, 2, 1, 0.5, 0.2, 0.1, 0.05, 0.01]
              weight_decay: 
                values: [0.001, 0.005, 0.01, 0.05, 0.1, 0.2, 0.5, 1, 2, 5]
