command:
  - uv
  - run
  - src/fast_gnn_benchmark/sweep/agent.py
name: pokec_sage_cluster_sweep
method: bayes # random, grid, bayes
metric:
  goal: maximize
  name: test/accuracy
parameters:
  base_config_file:
    values:
      - configs/pokec/sage_cluster.yml
  data_parameters:
    parameters:
      train_data_loader_parameters:
        parameters:
          num_clusters:
            values: 
            - 100
            - 200
            - 500
            - 1000
            - 1500
            - 2000
            - 3000
          num_parts:
            values: [2, 3, 5, 10, 15, 20, 25]
  model_parameters:
    parameters:
      architecture_parameters:
        parameters:
          dropout:
            values: [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8]

      optimizer:
        parameters:
          parameters:
            parameters:
              lr: 
                values: [0.05, 0.01, 0.005, 0.001, 0.0005, 0.0001]
              weight_decay: 
                values: [0, 0.0001, 0.0005, 0.001, 0.005, 0.01]


